import Image from "next/image"
import { ArrowUpRight, Check, ChevronRight, Leaf, PackageCheck, ShoppingBasket, Store, Truck, Users, Utensils } from "lucide-react"

const catalog = "https://chikeun.katalogku.online"
const whatsapp = "https://wa.me/6285220521882"
const products = [
  ["Ayam Broiler", "Fresh whole chicken", "/images/ayam-broiler.png"],
  ["Fillet Paha", "Fresh chicken thigh fillet", "/images/fillet-paha.png"],
  ["Ceker", "Fresh chicken feet", "/images/ceker.png"],
  ["Ati Ampela", "Chicken liver & gizzard", "/images/ati-ampela.png"],
]
const why = [[Leaf, "Produk Segar", "Produk ayam segar untuk kebutuhan rumah maupun usaha."], [ShoppingBasket, "Praktis", "Pesan produk dengan mudah melalui katalog online atau WhatsApp."], [PackageCheck, "Harga Transparan", "Lihat informasi produk dan harga melalui katalog CHIKEUN."], [Users, "Rumah & Bisnis", "Cocok untuk kebutuhan keluarga maupun usaha kuliner."]]

function Logo() { return <a href="#home" className="logo"><span>CHIKEUN</span><small>AYAM & PRODUK AYAM</small></a> }
function Button({ href, children, dark = false }: { href: string; children: React.ReactNode; dark?: boolean }) { return <a href={href} className={`button ${dark ? "button-dark" : ""}`}>{children}<ArrowUpRight size={16} /></a> }

export default function Home() {
  return <main>
    <header className="nav-wrap"><nav className="nav container"><Logo /><div className="nav-links"><a href="#products">Products</a><a href="#why">Why CHIKEUN</a><a href="#business">For Business</a><a href="#order">How to Order</a></div><Button href={catalog}>Lihat Katalog</Button><details className="mobile-menu"><summary>Menu</summary><div><a href="#products">Products</a><a href="#why">Why CHIKEUN</a><a href="#business">For Business</a><a href="#order">How to Order</a></div></details></nav></header>
    <section id="home" className="hero container"><div className="hero-copy"><p className="eyebrow"><span className="dot" /> AYAM SEGAR & PRODUK AYAM</p><h1>Stok Ayam <em>CHIKEUN,</em><br /> Tinggal Pesan<span>.</span></h1><p className="lede">Ayam segar berkualitas untuk kebutuhan rumah, warung, katering, restoran, dan usaha kuliner.</p><div className="actions"><Button href={catalog}>Lihat Produk & Harga</Button><a className="text-link" href={whatsapp}>Pesan via WhatsApp <ChevronRight size={17} /></a></div><div className="trust"><span><Check size={15} /> Fresh</span><span><Check size={15} /> Praktis</span><span><Check size={15} /> Terpercaya</span></div></div><div className="hero-visual"><div className="hero-image"><Image src="/images/hero-chicken.png" alt="Fresh whole chicken from CHIKEUN" fill priority sizes="(max-width: 800px) 100vw, 50vw" /></div><span className="quality-badge">FRESH<br /><b>& QUALITY</b></span><span className="stock-badge">STOK<br /><b>HARI INI</b></span><span className="scribble">fresh every day</span></div></section>
    <section id="products" className="section container"><div className="section-head"><div><p className="eyebrow">PILIHAN HARI INI</p><h2>Produk <em>CHIKEUN</em></h2></div><p>Dari dapur rumah hingga operasional usaha,<br className="desktop" /> pilih ayam segar sesuai kebutuhanmu.</p></div><div className="product-grid">{products.map(([name, desc, image]) => <article className="product-card" key={name}><div className="product-image"><Image src={image} alt={name} fill sizes="(max-width: 700px) 45vw, 25vw" /></div><div className="product-info"><h3>{name}</h3><p>{desc}</p><a href={catalog}>Lihat Detail <ArrowUpRight size={15} /></a></div></article>)}</div><div className="center"><Button href={catalog} dark>Lihat Semua Produk</Button></div></section>
    <section id="why" className="why section"><div className="container"><div className="section-head"><div><p className="eyebrow">KENAPA KAMI</p><h2>Alasan pilih <em>CHIKEUN?</em></h2></div><p>Kami menjaga hal-hal penting tetap<br className="desktop" /> sederhana untuk kamu.</p></div><div className="why-grid">{why.map(([Icon, title, text]) => <article key={title as string}><div className="icon-box"><Icon size={22} /></div><h3>{title as string}</h3><p>{text as string}</p></article>)}</div></div></section>
    <section id="business" className="business section container"><div className="business-image"><Image src="/images/fillet-paha.png" alt="Fresh chicken supply for food businesses" fill sizes="(max-width: 800px) 100vw, 45vw" /></div><div className="business-copy"><p className="eyebrow">UNTUK USAHA</p><h2>Butuh Ayam<br /><em>untuk Usaha?</em></h2><p>CHIKEUN siap membantu kebutuhan ayam untuk warung makan, katering, restoran, UMKM kuliner, dan bisnis makanan lainnya.</p><div className="chips"><span><Store size={16} /> Warung Makan</span><span><Utensils size={16} /> Katering</span><span><Store size={16} /> Restoran</span><span><Users size={16} /> UMKM Kuliner</span></div><Button href={whatsapp}>Konsultasi via WhatsApp</Button><small>Diskusikan kebutuhan jumlah, jenis produk, dan jadwal pengadaan ayam bersama CHIKEUN.</small></div></section>
    <section id="order" className="order section"><div className="container"><div className="center"><p className="eyebrow">CARA PESAN</p><h2>Pesan Ayam Jadi <em>Lebih Mudah</em></h2></div><div className="steps">{[["01", "Lihat Katalog", "Jelajahi produk CHIKEUN melalui katalog online."], ["02", "Pilih Produk", "Pilih jenis dan jumlah produk sesuai kebutuhan."], ["03", "Pesan", "Hubungi CHIKEUN melalui WhatsApp untuk konfirmasi pesanan."]].map(([num, title, text]) => <div className="step" key={num}><b>{num}</b><div><h3>{title}</h3><p>{text}</p></div></div>)}</div><div className="center"><Button href={catalog} dark>Mulai Belanja</Button></div></div></section>
    <section className="final container"><div><p className="eyebrow">SIAP UNTUK HARI INI?</p><h2>Siap Stok Ayam<br /><em>di Rumah?</em></h2><p>Lihat pilihan produk CHIKEUN dan pesan sesuai kebutuhan kamu.</p></div><div className="final-actions"><Button href={catalog}>Lihat Produk & Harga</Button><a className="text-link light" href={whatsapp}>Chat WhatsApp <ChevronRight size={17} /></a></div><div className="final-leaf"><Leaf size={120} strokeWidth={1} /></div></section>
    <footer className="footer"><div className="container footer-grid"><div><Logo /><p>Ayam segar dan produk ayam<br />untuk kebutuhan rumah dan usaha.</p></div><div><b>Explore</b><a href="#products">Products</a><a href="#why">Why CHIKEUN</a><a href="#business">For Business</a></div><div><b>Contact</b><a href={whatsapp}>0852 2052 1882</a><a href={catalog}>chikeun.katalogku.online</a></div></div><div className="container footer-bottom"><span>© 2026 CHIKEUN. All rights reserved.</span><span>Made fresh, made simple.</span></div></footer>
    <div className="mobile-cta"><a href={catalog}>Lihat Katalog</a><a href={whatsapp}>WhatsApp</a></div>
  </main>
}
